// File generated by FlutterFire CLI (editado para seguimientomapacnt).
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Si NO usas web, puedes dejarlo así (placeholder).

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeYSr7fzxtzXizwaHJWKhBvpNJSqbUAhQ',
    appId: '1:813832519846:web:eb62c67453a7c1a051f467',
    messagingSenderId: '813832519846',
    projectId: 'seguimientomapacnt',
    authDomain: 'seguimientomapacnt.firebaseapp.com',
    storageBucket: 'seguimientomapacnt.firebasestorage.app',
    measurementId: 'G-SKVWW9VG1K',
  );

  // Si en algún momento usas web, vuelve a correr flutterfire configure para web.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmGYbMS5T2_R0t55N6s6vBDNRjiIy481s',
    appId: '1:813832519846:android:e2e3a87c5f911dd751f467',
    messagingSenderId: '813832519846',
    projectId: 'seguimientomapacnt',
    storageBucket: 'seguimientomapacnt.firebasestorage.app',
  );

  // ✅ ANDROID (tomado de tu google-services.json)

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLE245pUVcvxmbBzDrQ7vZ7zEaP0rQ6dk',
    appId: '1:813832519846:ios:3b46d88f42612abd51f467',
    messagingSenderId: '813832519846',
    projectId: 'seguimientomapacnt',
    storageBucket: 'seguimientomapacnt.firebasestorage.app',
    iosBundleId: 'com.example.seguimientomapacnt',
  );

  // Placeholders (solo importan si compilas iOS/macos)

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLE245pUVcvxmbBzDrQ7vZ7zEaP0rQ6dk',
    appId: '1:813832519846:ios:3b46d88f42612abd51f467',
    messagingSenderId: '813832519846',
    projectId: 'seguimientomapacnt',
    storageBucket: 'seguimientomapacnt.firebasestorage.app',
    iosBundleId: 'com.example.seguimientomapacnt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeYSr7fzxtzXizwaHJWKhBvpNJSqbUAhQ',
    appId: '1:813832519846:web:dfc5b006b5448c8251f467',
    messagingSenderId: '813832519846',
    projectId: 'seguimientomapacnt',
    authDomain: 'seguimientomapacnt.firebaseapp.com',
    storageBucket: 'seguimientomapacnt.firebasestorage.app',
    measurementId: 'G-NX8CMVGP4D',
  );

}